apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gatus.fullname" . }}
  namespace: {{ template "gatus.namespace" . }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.persistence.enabled }}
    storage: {{- toYaml .Values.persistence.storage | nindent 6 }}
    {{- end }}
    {{- toYaml .Values.config | nindent 4 }}
