name: Test Workflow
on: [push]
jobs:
  test:
    name: Test with helm@${{ matrix.helm }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm: [2.17.0]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: azure/setup-helm@v1
      with:
        version: ${{ matrix.helm }}
    - name: Lint
      run: make lint
